from __future__ import annotations

import argparse
import hashlib
import json
import struct
import sys
from pathlib import Path
from typing import Iterable

import numpy as np
import torch

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))

from model import TinyEnhancerCNN, transform_outputs

ORDER = [
    ("conv1W", "conv1.weight"),
    ("conv1B", "conv1.bias"),
    ("dw2W", "dw2.weight"),
    ("dw2B", "dw2.bias"),
    ("pw2W", "pw2.weight"),
    ("pw2B", "pw2.bias"),
    ("dw3W", "dw3.weight"),
    ("dw3B", "dw3.bias"),
    ("pw3W", "pw3.weight"),
    ("pw3B", "pw3.bias"),
    ("dw4W", "dw4.weight"),
    ("dw4B", "dw4.bias"),
    ("pw4W", "pw4.weight"),
    ("pw4B", "pw4.bias"),
    ("fc1W", "fc1.weight"),
    ("fc1B", "fc1.bias"),
    ("fc2W", "fc2.weight"),
    ("fc2B", "fc2.bias"),
]


def floats(values: Iterable[float]) -> str:
    return ",".join(f"{float(value):.9g}" for value in values)


def c_floats(values: Iterable[float]) -> str:
    return ",".join(f"{float(value):.9g}f" for value in values)


def generate_typescript(weights: dict[str, np.ndarray], output: Path) -> None:
    lines = [
        "// Generated by training/export_model.py. Do not edit manually.",
        "export const MODEL_INPUT_SIZE = 64;",
        "export const MODEL_WEIGHTS = {",
    ]
    for public_name, _ in ORDER:
        values = weights[public_name].reshape(-1)
        lines.append(f"  {public_name}: new Float32Array([{floats(values)}]),")
    lines.extend(["} as const;", ""])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")


def generate_c(weights: dict[str, np.ndarray], output: Path) -> None:
    arrays = []
    for public_name, _ in ORDER:
        values = weights[public_name].reshape(-1)
        arrays.append(
            f"static const float {public_name}[{values.size}] = {{{c_floats(values)}}};"
        )
    source = f'''// Generated by training/export_model.py. Do not edit manually.
{chr(10).join(arrays)}

static float model_input[64 * 64 * 3];
static float model_output[4];
static float b1[32 * 32 * 8];
static float b2d[16 * 16 * 8];
static float b2[16 * 16 * 16];
static float b3d[8 * 8 * 16];
static float b3[8 * 8 * 24];
static float b4d[4 * 4 * 24];
static float b4[4 * 4 * 32];
static float gap[32];
static float hidden[16];

static float relu(float value) {{ return value > 0.0f ? value : 0.0f; }}

int input_ptr(void) {{ return (int)model_input; }}
int output_ptr(void) {{ return (int)model_output; }}

void infer(void) {{
  for (int oy = 0; oy < 32; ++oy) {{
    for (int ox = 0; ox < 32; ++ox) {{
      for (int oc = 0; oc < 8; ++oc) {{
        float sum = conv1B[oc];
        for (int ky = 0; ky < 3; ++ky) {{
          const int iy = oy * 2 + ky - 1;
          if (iy < 0 || iy >= 64) continue;
          for (int kx = 0; kx < 3; ++kx) {{
            const int ix = ox * 2 + kx - 1;
            if (ix < 0 || ix >= 64) continue;
            for (int ic = 0; ic < 3; ++ic) {{
              const int input_index = (iy * 64 + ix) * 3 + ic;
              const int weight_index = ((oc * 3 + ic) * 3 + ky) * 3 + kx;
              sum += model_input[input_index] * conv1W[weight_index];
            }}
          }}
        }}
        b1[(oy * 32 + ox) * 8 + oc] = relu(sum);
      }}
    }}
  }}

  for (int oy = 0; oy < 16; ++oy) {{
    for (int ox = 0; ox < 16; ++ox) {{
      for (int c = 0; c < 8; ++c) {{
        float sum = dw2B[c];
        for (int ky = 0; ky < 3; ++ky) {{
          const int iy = oy * 2 + ky - 1;
          if (iy < 0 || iy >= 32) continue;
          for (int kx = 0; kx < 3; ++kx) {{
            const int ix = ox * 2 + kx - 1;
            if (ix < 0 || ix >= 32) continue;
            sum += b1[(iy * 32 + ix) * 8 + c] * dw2W[c * 9 + ky * 3 + kx];
          }}
        }}
        b2d[(oy * 16 + ox) * 8 + c] = sum;
      }}
      for (int oc = 0; oc < 16; ++oc) {{
        float sum = pw2B[oc];
        for (int ic = 0; ic < 8; ++ic) {{
          sum += b2d[(oy * 16 + ox) * 8 + ic] * pw2W[oc * 8 + ic];
        }}
        b2[(oy * 16 + ox) * 16 + oc] = relu(sum);
      }}
    }}
  }}

  for (int oy = 0; oy < 8; ++oy) {{
    for (int ox = 0; ox < 8; ++ox) {{
      for (int c = 0; c < 16; ++c) {{
        float sum = dw3B[c];
        for (int ky = 0; ky < 3; ++ky) {{
          const int iy = oy * 2 + ky - 1;
          if (iy < 0 || iy >= 16) continue;
          for (int kx = 0; kx < 3; ++kx) {{
            const int ix = ox * 2 + kx - 1;
            if (ix < 0 || ix >= 16) continue;
            sum += b2[(iy * 16 + ix) * 16 + c] * dw3W[c * 9 + ky * 3 + kx];
          }}
        }}
        b3d[(oy * 8 + ox) * 16 + c] = sum;
      }}
      for (int oc = 0; oc < 24; ++oc) {{
        float sum = pw3B[oc];
        for (int ic = 0; ic < 16; ++ic) {{
          sum += b3d[(oy * 8 + ox) * 16 + ic] * pw3W[oc * 16 + ic];
        }}
        b3[(oy * 8 + ox) * 24 + oc] = relu(sum);
      }}
    }}
  }}

  for (int oy = 0; oy < 4; ++oy) {{
    for (int ox = 0; ox < 4; ++ox) {{
      for (int c = 0; c < 24; ++c) {{
        float sum = dw4B[c];
        for (int ky = 0; ky < 3; ++ky) {{
          const int iy = oy * 2 + ky - 1;
          if (iy < 0 || iy >= 8) continue;
          for (int kx = 0; kx < 3; ++kx) {{
            const int ix = ox * 2 + kx - 1;
            if (ix < 0 || ix >= 8) continue;
            sum += b3[(iy * 8 + ix) * 24 + c] * dw4W[c * 9 + ky * 3 + kx];
          }}
        }}
        b4d[(oy * 4 + ox) * 24 + c] = sum;
      }}
      for (int oc = 0; oc < 32; ++oc) {{
        float sum = pw4B[oc];
        for (int ic = 0; ic < 24; ++ic) {{
          sum += b4d[(oy * 4 + ox) * 24 + ic] * pw4W[oc * 24 + ic];
        }}
        b4[(oy * 4 + ox) * 32 + oc] = relu(sum);
      }}
    }}
  }}

  for (int c = 0; c < 32; ++c) {{
    float sum = 0.0f;
    for (int i = 0; i < 16; ++i) sum += b4[i * 32 + c];
    gap[c] = sum * 0.0625f;
  }}

  for (int oc = 0; oc < 16; ++oc) {{
    float sum = fc1B[oc];
    for (int ic = 0; ic < 32; ++ic) sum += gap[ic] * fc1W[oc * 32 + ic];
    hidden[oc] = relu(sum);
  }}

  for (int oc = 0; oc < 4; ++oc) {{
    float sum = fc2B[oc];
    for (int ic = 0; ic < 16; ++ic) sum += hidden[ic] * fc2W[oc * 16 + ic];
    model_output[oc] = sum;
  }}
}}
'''
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(source, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", type=Path, default=ROOT / "training" / "checkpoints" / "baseline.pt")
    args = parser.parse_args()

    checkpoint = torch.load(args.checkpoint, map_location="cpu", weights_only=False)
    model = TinyEnhancerCNN()
    model.load_state_dict(checkpoint["state_dict"])
    model.eval()

    weights: dict[str, np.ndarray] = {}
    for public_name, state_name in ORDER:
        weights[public_name] = checkpoint["state_dict"][state_name].detach().cpu().numpy().astype(np.float32)

    generate_typescript(weights, ROOT / "src" / "ml" / "modelWeights.ts")
    generated_c = ROOT / "training" / "generated" / "model.c"
    generate_c(weights, generated_c)

    binary = b"".join(struct.pack("<f", float(value)) for public_name, _ in ORDER for value in weights[public_name].reshape(-1))
    (ROOT / "public" / "assets").mkdir(parents=True, exist_ok=True)
    (ROOT / "public" / "assets" / "model-weights.bin").write_bytes(binary)

    metadata = {
        "version": "1.0.0",
        "architecture": "tiny-cnn-v1",
        "input": {"width": 64, "height": 64, "channels": 3, "layout": "HWC", "range": [-1, 1]},
        "outputs": ["exposureEV", "contrast", "saturation", "correctionStrength"],
        "ranges": {
            "exposureEV": [-1.25, 1.25],
            "contrast": [0.55, 1.45],
            "saturation": [0.5, 1.5],
            "correctionStrength": [0, 1]
        },
        "parameterCount": int(sum(value.size for value in weights.values())),
        "weightBytes": len(binary),
        "weightSha256": hashlib.sha256(binary).hexdigest(),
        "training": {
            "seed": checkpoint.get("seed"),
            "epoch": checkpoint.get("epoch"),
            "validationMetrics": checkpoint.get("metrics")
        }
    }
    (ROOT / "public" / "assets" / "model.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    rng = np.random.default_rng(7781)
    vectors = []
    with torch.no_grad():
        for index in range(3):
            image = rng.integers(0, 256, size=(64, 64, 3), dtype=np.uint8)
            tensor = torch.from_numpy(image).permute(2, 0, 1).float().unsqueeze(0) / 127.5 - 1.0
            raw = model(tensor)[0].numpy().tolist()
            transformed = transform_outputs(model(tensor))[0].numpy().tolist()
            vectors.append({
                "id": f"random-{index}",
                "inputBase64": __import__("base64").b64encode(image.tobytes()).decode("ascii"),
                "raw": raw,
                "transformed": transformed
            })
    fixtures = ROOT / "tests" / "fixtures"
    fixtures.mkdir(parents=True, exist_ok=True)
    (fixtures / "model-vectors.json").write_text(json.dumps(vectors), encoding="utf-8")
    print(json.dumps(metadata, indent=2))


if __name__ == "__main__":
    main()
